### PR TITLE
Adding find movie by IMDB id feature

### PR DESCRIPTION
**Pull request by AlanCS**
Added "FindByIMDBIdAsync" feature to Movie API, and fixed a few tests :)

### CODE REVIEW

**Comment by nCubed** [comment]
@AlanCS - Before adding this into the wrapper, I'd like to better understand the use case. Can you please describe the use case for a search by IMDB Id?

**Comment by AlanCS** [comment]
of course :)
if you want to get a list of movies off the internet, specially a pre-selected list (like https://www.imdb.com/list/ls000064466/) you are likely to only have a list of IMDB ids, so that's method will be incredibly useful here.

you could search for name and year, but that could return some duplicates and even if it didn't, you would have to make another call to get the details; so a search by IMDB id is both more precise and less work

**Comment by nCubed** [comment]
@AlanCS The project was neglected for a bit and is now back! I've upgraded the project to use VS 2019 and published a new release. If the find by IMDB Id is still needed, let me know. May have to manually port your changes, but should be fairly easy since it looks like you followed the general conventions, which is awesome btw!

**Comment by AlanCS** [comment]
> @AlanCS The project was neglected for a bit and is now back! I've upgraded the project to use VS 2019 and published a new release. If the find by IMDB Id is still needed, let me know. May have to manually port your changes, but should be fairly easy since it looks like you followed the general conventions, which is awesome btw!

thank

I was just using for a personal project that didn't go ahead; so I don't intend to make any further changes

all the best

**Pull request closed without merging**
