### PR TITLE
Discover movies

### PR DESCRIPTION
**Pull request by bariscanyilmaz**
Discover movie feature receives movies with defined parameters like cast, crew, genre, without genre and original language

### CODE REVIEW

**Review by nCubed — CHANGES_REQUESTED** [review]
Several of the comments I added to #45 are relevant for this PR as well. Please review #45 and then make the same/similar changes to #46. Thanks!

**Comment by bariscanyilmaz** [comment]
@nCubed could you review

**Comment by nCubed** [comment]
Holding off until we resolve #45 (similar comments would apply to this PR as well)

**Comment by nCubed** [comment]
I am merging this PR into a new branch and will fix as-needed.

**Pull request merged**
