### PR TITLE
[ADD] Keywords request

### PR DESCRIPTION
**Pull request by Rhada**
Add posibility to request keywords related to a movie

### CODE REVIEW

**Comment by nCubed** [comment]
@Rhada - Great addition! 

I'm thinking there may be conflicts if the Keywords are limited to just movies; the TV api also has Keywords that should be accounted for.

A couple of questions:

1. What do you think about removing the `Keywords` class as it is only wrapping the results? This could lead to something similar we did with `Genres` by simply placing them on the primary Movie class.

2. Would you be able to add an IEqualityComparer<Keyword> to the `Keyword` class?

3. We'd need to include new integration tests for Keywords; is that something you'd be able to tackle?

Before items 2 and 3 are completed (either by yourself of me), we need to come up with a more generalized solution for bringing in the Keywords so they work with both Movies and TV.

**Comment by nCubed** [comment]
@Rhada - I'm going to do a bit of clean-up to the project and convert to some of the newer C# 6 syntax. If you're OK, I'll go ahead and take your pull request and put the final touches on it such as pulling out the wrapping Keywords class and getting the information into the Movie class.

**Comment by nCubed** [comment]
@Rhada - I've added keywords to all movie requests by using an append_to_response with the query to themoviedb api. I've also published the latest package on Nuget. Let me know if this works for you.

**Comment by Rhada** [comment]
Yes it's working. Thank you  !  What do you think about split entities into an other DLL ?

**Comment by nCubed** [comment]
Typically, I'd create an assembly with just the entities. In this case, the entities here are tightly coupled to the API and I'd like to keep them all in the same assembly.

Other than the typical SRP concerns, do you have a use case for separating the entities into a new assembly?

**Pull request merged**
